### PR TITLE
Improvement for FileUploader Addin

### PR DESCRIPTION
**Pull request by masterdany88**
I've added support for Unauthorised response from server. I've added unauthorized event also.

I've added response body parameter in Response object. Thanks to it we can send any information back from server to client, f.e.: new file name string.

My commits should fill demands:
https://github.com/GwtMaterialDesign/gwt-material-addins/issues/77
https://github.com/GwtMaterialDesign/gwt-material-addins/pull/78

### CODE REVIEW

**Comment by BenDol** [comment]
Thanks for the contribution @masterdany88. We need this fix made against the `release_1.5.2` branch rather than `master` branch. Thanks!

**Comment by masterdany88** [comment]
Ok. Should I recommit it again to correct branch? Or You can change commit branch?

**Comment by BenDol** [comment]
When you create the Pull Request just select the `release_1.5.2 branch.

**Comment by masterdany88** [comment]
But I can only choose 1.5.0, 1.5.1 i 1.6.0 versions. There is no 1.5.2
image

**Comment by BenDol** [comment]
Seems that you haven't fetched the latest changed from the `upstream`. You need to do the update as stated here and it will show up. https://github.com/GwtMaterialDesign/gwt-material/wiki/Contributing#updating-your-fork

**Comment by kevzlou7979** [comment]
@masterdany88 Ive created now the 1.5.2 branch

**Comment by kevzlou7979** [comment]
Whats the update into this PR? The branch 1.5.2 is now ready, just close this and create another PR to 1.5.2. Btw thanks for the PR.

**Pull request closed without merging**
