### PR TITLE
fixed #92: "MaterialAutoComplete.setFocus(true) does nothing"

### LINKED ISSUE #92: MaterialAutoComplete.setFocus(true) does nothing
It appears that the call to **uiObject.getElement().focus()** in **FocusableMixin.java** results in **focus()** getting called on the underlying **DIV**, rather than on the **INPUT**, which is nested 3 levels deeper.
The issue is related to **AutocompleteType.CHIP**
GMD 1.5.1, GMA 1.5.1

### PR DESCRIPTION
**Pull request by jzaruba**
I have created/cloned a new focusableMixin field in MaterialAutoComplete. (The one in MaterialWidget is private hence I could not access it.) The original one is never accessed directly though, and I have overriden the getter, so there should be no issue.
The new focusableMixin instance is created from itemBox.getElement().
MaterialAutoComplete.setFocus() now correctly puts focus into the HtmlInputElement of the widget.
Tested in Chrome, Firefox, MSIE.

### CODE REVIEW

**Comment by jzaruba** [comment]
[I see The Travis CI build has failed.](https://travis-ci.org/GwtMaterialDesign/gwt-material-addins/builds/139922926) The error message looks like it was maybe building with the old MaterialWidget where getFocusableMixin is still private, i.e. the @Override annotation resulted in overriding a private method...?
From the log I can't tell where was the gwt-material:1.6.0-SNAPSHOT downloaded from. (But for example the one in [Sonatype snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/gwt-material/1.6.0-SNAPSHOT/) seems to be updated already.)

**Comment by jzaruba** [comment]
I'm wondering, did Ci even try to use 1.6.0-SNAPSHOT?
`[INFO] Building jar: /home/travis/build/GwtMaterialDesign/gwt-material-addins/gwt-material/gwt-material/target/gwt-material-1.5.1.jar
`

**Comment by kevzlou7979** [comment]
Ok I found the issue its on travis.ci the file has wrong branch to be build it;s ``` release_1.5.1 ``` instead of 1.6.0 will fix now the issue

**Comment by kevzlou7979** [comment]
Please update now your ``` release_1.6.0 ``` branch and merge it to the remote branch so that it will solve the Travis. Again thanks for the contribution :)

Here is the reference that the travis is working now https://travis-ci.org/GwtMaterialDesign/gwt-material-addins

**Comment by jzaruba** [comment]
I am sorry, my experience with Git spans over few months.
What do you mean by updating my release_1.6.0? Do you mean merging **GwtMaterialDesign/gwt-material-addins/release_1.6.0** into my local **jzaruba/gwt-material-addins/release_1.6.0**...? I have just done that. Now I have two Modified files: .travis.yml and deploy.sh. That makes sense.
I suppose now I need to commit/push only if I want to keep my release_1.6.0 identical to yours. That would be another way of doing what you recommend here: [Updating Your Fork](https://github.com/GwtMaterialDesign/gwt-material/wiki/Contributing):
`git pull --rebase upstream master # Note that this pulls from master branch (can be changed)`
Am I right? (In other words, no action needs to be done on my side to complete the fix.)
P.S.: I want to keep my branch up-to-date of course, just trying to understand the flow.

**Comment by jzaruba** [comment]
Ah oops, the pull request needs to be actually repeated, right? Which is why I need to commit/push those two changes so I can then make new PR.

**Comment by jzaruba** [comment]
Oh the wonders of modern tekkmology! :) Have I just triggerred PR retry just by merging your 1.6.0 into mine? Neat!

**Comment by kevzlou7979** [comment]
Ok ready to go :) Will check the code

**Comment by kevzlou7979** [comment]
Can this be applicable also to MaterialValueBox component like text box, number box etc. ?

**Comment by jzaruba** [comment]
Seems so... Looking at the code of MaterialValueBox, **ValueBoxBase<T> valueBoxBase** would be used for the FocusableMixin.
I will try it.

**Comment by kevzlou7979** [comment]
Ok thanks, will remain this open for code review :)

**Pull request merged**
