### PR TITLE
Add thickness property in px for MaterialSplitPanel

### PR DESCRIPTION
**Pull request by andersforsell**
This is in alignment with the 2.0 version's addition of the thickness property, but I would be happy to get it already in 1.6

### CODE REVIEW

**Comment by kevzlou7979** [comment]
Can you update the pr branch to 1.6.0, thanks

**Comment by andersforsell** [comment]
Oh, switching to 1.6.0 resulted in conflicts I guess...

**Comment by kevzlou7979** [comment]
There are files that does not need to be changed (8files) , its just the MaterialSplitPanel (no more files). Please recreate the PR then we can merge this in.

**Comment by andersforsell** [comment]
Created https://github.com/GwtMaterialDesign/gwt-material-addins/pull/128 based on 1.6.0

**Pull request closed without merging**
