### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by kevzlou7979**
- MaterialRating ([NEW](http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#rating)) 
	- the component used by the 5-star rating (Thanks to @gilberto-torrezan)
- MaterialAvatar ([NEW](http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#avatar))
	- based from [jdenticon](https://jdenticon.com/) - a free js library for generating highly reognizable identicons 
- Refactor
	- Convert all private methods to protected to allow overriding of API
- MaterialAutocomplete
	- fixed setFocus(true) (Thanks to @jzaruba).
- MaterialFileUploader
	- fixed styles on upload preview collections.
- Support for helper texts.
- MaterialRichEditor
	- support for pasteHTML (Thanks to @jyeakley).
	- added blur, focus, keyup, keydown, paste and change events.
	- added disableDragAndDrop() feature.
- MaterialSplitPanel
	- add ```thickness``` property (Thanks to @andersforsell).
- MaterialTimePicker
	- Fixed styles (Disabled state, horizontal and vertical spacing).
	- Added support for icons
- MaterialAutocomplete
	- Fixed styles (Disabled state, horizontal and vertical spacing).

### CODE REVIEW

**Comment by masterdany88** [comment]
How about my FileUploader https://github.com/GwtMaterialDesign/gwt-material-addins/pull/109 ?

**Comment by andersforsell** [comment]
Nice! I cannot see 1.6.0 of gwt-material-addins in Maven Central only gwt-material, why is that?

**Comment by kevzlou7979** [comment]
We are releasing it (On Going) all gwt-material related projects :)

**Comment by kevzlou7979** [comment]
We will post later on Gplus and on Gitter about the official release :) Keep updated

**Comment by andersforsell** [comment]
Thumbs up!

**Pull request merged**
