### PR TITLE
Implementation of RichEditor

### PR DESCRIPTION
**Pull request by kevzlou7979**

### CODE REVIEW

**Comment by BenDol** [comment]
Not sure we should be using a bootstrap library in a material design UI. Summernote is great but adding another dependency to a large library like bootstrap when we already load others could be a bad idea.

**Comment by kevzlou7979** [comment]
Can u suggest some rich editor for alternative?

**Comment by BenDol** [comment]
Something like https://www.tinymce.com could work a lot better, its very lightweight.

**Comment by kevzlou7979** [comment]
ok will close this then try tinymce :)

**Pull request closed without merging**
